LANG=zh_CN.GB2312
LC_ALL=zh_CN.GB2312
LC_CTYPE=zh_CN.GB2312
KDE_LANG=zh_CN.GB2312
XMODIFIERS=@im=fcitx
XIM=fcitx
XIM_PROGRAM=fcitx
export LANG LC_ALL LC_CTYPE KDE_LANG XMODIFIERS XIM XIM_PROGRAM
fcitx &
/opt/kde/bin/startkde
#xterm
# xloadimage -onroot -zoom 79 /usr/share/images/desktop-base/Debian.jpg
# metacity --sm-disable &
# exec crxvt

# exec startxfce4
# exec wmaker
# exec fvwm2
# exec icewm

# Use xfce
# xfce-mcs-manager
# xfwm4 --daemon
# xftaskbar4 &
# xfdesktop &
# exec xfce4-panel
